import streamlit as st
import sys
import os
import json

# Ensure the parent directory is in sys.path so we can import from agent_stub
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
STREAMLIT_APP_DIR = os.path.dirname(CURRENT_DIR)
CODE_DIR = os.path.dirname(STREAMLIT_APP_DIR)
REPO_ROOT = os.path.dirname(CODE_DIR)

if STREAMLIT_APP_DIR not in sys.path:
    sys.path.insert(0, STREAMLIT_APP_DIR)

from agent_stub import _query_cortex_analyst, _ask_via_ollama
from snowflake_conn import get_active_session
from wizard import is_infrastructure_ready

st.set_page_config(page_title="Data Analyst", page_icon="📊", layout="wide")

st.title("📊 Cortex Analyst Playground")
st.markdown("Interact directly with the semantic model using natural language.")

# Initialize chat history
if "analyst_messages" not in st.session_state:
    st.session_state["analyst_messages"] = []

@st.cache_data
def analyze_semantic_model():
    yaml_path = os.path.join(REPO_ROOT, "semantic_models", "factory_health_ontology.yaml")
    try:
        with open(yaml_path, 'r') as f:
            yaml_content = f.read()
            
        prompt = f"""
You are an expert data analyst. I am providing you with a semantic model YAML file that describes a Snowflake database schema.

<semantic_model>
{yaml_content}
</semantic_model>

Please do two things:
1. Write a 5-10 sentence overview explaining what this dataset tracks and why it's useful to a factory manager.
2. Generate exactly 3 analytical questions a data analyst could ask this dataset purely to find out the trends of Overall Equipment Effectiveness (OEE). The questions MUST be simple and answerable using ONLY the metrics (temperature, vibration, stress score, RUL) and dimensions (equipment, SKU) explicitly defined in the provided semantic model. Do NOT ask for multi-layered correlations or complex root-cause analyses that aren't supported by these basic tables.

Return your response in EXACTLY this JSON format (no markdown, no backticks, just the JSON):
{{
  "overview": "Your 2-3 sentence overview here.",
  "questions": [
    "Question 1?",
    "Question 2?",
    "Question 3?"
  ]
}}
"""
        response = _ask_via_ollama(prompt).strip()
        
        # Clean up the response in case Ollama added markdown backticks
        if response.startswith("```json"):
            response = response[7:]
        if response.startswith("```"):
            response = response[3:]
        if response.endswith("```"):
            response = response[:-3]
            
        return json.loads(response.strip())
        
    except Exception as e:
        return {
            "overview": "*(Using fallback overview because Ollama generation failed)*\n\nA unified ontology mapping high-frequency physical machine telemetry to low-frequency ERP batch schedules to identify product-driven equipment degradation.",
            "questions": [
                "What is the average temperature for LINE-2-PACKAGING when producing SKU-899?",
                "Which SKUs cause the highest cumulative stress score?",
                "Show me the predicted failure timestamp for equipment with the lowest RUL."
            ]
        }

with st.spinner("🤖 Ollama is analyzing the Semantic Model..."):
    analysis = analyze_semantic_model()

# --- Explain Dataset Section ---
with st.expander("ℹ️ Explain the Dataset (factory_health_ontology)", expanded=False):
    st.markdown("**Dataset Overview (Generated by Ollama):**")
    st.markdown(analysis["overview"])

# --- Suggested Questions ---
st.markdown("### Suggested Questions (Generated by Ollama)")
cols = st.columns(3)
suggestions = analysis["questions"]

for i, col in enumerate(cols):
    with col:
        if st.button(suggestions[i], use_container_width=True):
            st.session_state["analyst_messages"].append({"role": "user", "content": suggestions[i]})
            
            session = get_active_session()
            if not is_infrastructure_ready(session):
                msg = "⚠️ Infrastructure Missing: Database objects not found. Please run the One-Click Setup."
                st.session_state["analyst_messages"].append({"role": "assistant", "content": msg, "needs_setup": True})
            else:
                with st.status("🧠 Cortex Analyst is working...", expanded=True) as status_box:
                    # We pass an empty context since this is a generic playground
                    answer = _query_cortex_analyst(suggestions[i], context={}, status=status_box)
                    status_box.update(label="Analysis complete!", state="complete", expanded=False)
                    
                st.session_state["analyst_messages"].append({"role": "assistant", "content": answer})
            st.rerun()

st.markdown("---")

# Display chat messages
for idx, msg in enumerate(st.session_state["analyst_messages"]):
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("needs_setup"):
            if st.button("🚀 Run One-Click Infrastructure Setup", key=f"setup_hist_{idx}"):
                st.session_state["show_infra_setup"] = True
                st.switch_page("app.py")

# Chat input
if prompt := st.chat_input("Ask Cortex Analyst about your data..."):
    st.session_state["analyst_messages"].append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)

    session = get_active_session()
    if not is_infrastructure_ready(session):
        msg = "⚠️ Infrastructure Missing: Database objects not found. Please run the One-Click Setup."
        st.session_state["analyst_messages"].append({"role": "assistant", "content": msg, "needs_setup": True})
        with st.chat_message("assistant"):
            st.write(msg)
            if st.button("🚀 Run One-Click Infrastructure Setup", key="setup_new"):
                st.session_state["show_infra_setup"] = True
                st.switch_page("app.py")
    else:
        with st.status("🧠 Cortex Analyst is working...", expanded=True) as status_box:
            answer = _query_cortex_analyst(prompt, context={}, status=status_box)
            status_box.update(label="Analysis complete!", state="complete", expanded=False)

        st.session_state["analyst_messages"].append({"role": "assistant", "content": answer})
        with st.chat_message("assistant"):
            st.write(answer)
