--aggregate your dynamic table into hourly intervals, capturing the equipment ID, average temperature, and average vibration.--
USE DATABASE OEE_COMMAND_CENTER;
USE SCHEMA FACTORY_FLOOR;



CREATE OR REPLACE VIEW V_EQUIPMENT_TEMP_HISTORY AS
SELECT 
    DATE_TRUNC('HOUR', TIMESTAMP) AS TS_HOUR,
    EQUIPMENT_ID,
    AVG(TEMPERATURE_C) AS AVG_TEMP
FROM IT_OT_CONVERGED
GROUP BY 1, 2;

CREATE OR REPLACE VIEW V_EQUIPMENT_VIBE_HISTORY AS
SELECT 
    DATE_TRUNC('HOUR', TIMESTAMP) AS TS_HOUR,
    EQUIPMENT_ID,
    AVG(VIBRATION_RMS) AS AVG_VIBE
FROM IT_OT_CONVERGED
GROUP BY 1, 2;

--generate independent forecasts for every unique piece of equipment in your dataset.--
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST EQUIPMENT_TEMP_FORECAST (
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'V_EQUIPMENT_TEMP_HISTORY'),
    SERIES_COLNAME => 'EQUIPMENT_ID',
    TIMESTAMP_COLNAME => 'TS_HOUR',
    TARGET_COLNAME => 'AVG_TEMP'
);

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST EQUIPMENT_VIBE_FORECAST (
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'V_EQUIPMENT_VIBE_HISTORY'),
    SERIES_COLNAME => 'EQUIPMENT_ID',
    TIMESTAMP_COLNAME => 'TS_HOUR',
    TARGET_COLNAME => 'AVG_VIBE'
);

--flags the exact hour the forecasted metrics breach the critical OEM threshold--
-- Generate predictions for the next 72 hours and store them in a table
CREATE OR REPLACE TABLE PREDICTED_TEMPERATURES AS
SELECT * FROM TABLE(EQUIPMENT_TEMP_FORECAST!FORECAST(FORECASTING_PERIODS => 72));

CREATE OR REPLACE TABLE PREDICTED_VIBRATIONS AS
SELECT * FROM TABLE(EQUIPMENT_VIBE_FORECAST!FORECAST(FORECASTING_PERIODS => 72));

-- Calculate Remaining Useful Life (RUL) by finding the first breach
CREATE OR REPLACE VIEW ASSET_RUL_PREDICTIONS AS
WITH temp_threshold AS (
    SELECT COALESCE(MAX(MAX_TEMP_LIMIT), 90.0) AS DYNAMIC_THRESHOLD
    FROM OEM_EQUIPMENT_THRESHOLDS
),
vibe_threshold AS (
    SELECT COALESCE(MAX(MAX_VIBRATION_LIMIT), 2.3) AS DYNAMIC_THRESHOLD
    FROM OEM_EQUIPMENT_THRESHOLDS
),
temp_rul AS (
    SELECT 
        p.SERIES AS EQUIPMENT_ID,
        MIN(p.TS) AS PREDICTED_FAILURE_TIMESTAMP,
        GREATEST(1, ROUND(TIMEDIFF('HOUR', CURRENT_TIMESTAMP(), MIN(p.TS)), 1)) AS RUL_HOURS,
        'Temperature Forecast Breach' AS PREDICTIVE_CAUSE
    FROM PREDICTED_TEMPERATURES p
    CROSS JOIN temp_threshold t
    WHERE p.FORECAST >= t.DYNAMIC_THRESHOLD
    GROUP BY p.SERIES
),
vibe_rul AS (
    SELECT 
        p.SERIES AS EQUIPMENT_ID,
        MIN(p.TS) AS PREDICTED_FAILURE_TIMESTAMP,
        GREATEST(1, ROUND(TIMEDIFF('HOUR', CURRENT_TIMESTAMP(), MIN(p.TS)), 1)) AS RUL_HOURS,
        'Vibration Forecast Breach' AS PREDICTIVE_CAUSE
    FROM PREDICTED_VIBRATIONS p
    CROSS JOIN vibe_threshold t
    WHERE p.FORECAST >= t.DYNAMIC_THRESHOLD
    GROUP BY p.SERIES
),
combined_rul AS (
    SELECT * FROM temp_rul
    UNION ALL
    SELECT * FROM vibe_rul
)
-- Take the earliest predicted failure for each equipment
SELECT 
    EQUIPMENT_ID,
    PREDICTED_FAILURE_TIMESTAMP,
    RUL_HOURS,
    PREDICTIVE_CAUSE
FROM combined_rul
QUALIFY ROW_NUMBER() OVER (PARTITION BY EQUIPMENT_ID ORDER BY RUL_HOURS ASC) = 1;