USE ROLE ACCOUNTADMIN;

USE DATABASE OEE_COMMAND_CENTER;
USE SCHEMA FACTORY_FLOOR;

-- 1. Create the internal stage
CREATE STAGE IF NOT EXISTS OEM_MANUALS_STAGE
    DIRECTORY = (ENABLE = TRUE);

-- 3. Refresh stage directory metadata
ALTER STAGE OEM_MANUALS_STAGE REFRESH;

-- 4. Verify the uploaded file
SELECT *
FROM DIRECTORY(@OEM_MANUALS_STAGE);