-- run this in snowflake account worksheet--
CREATE TABLE IF NOT EXISTS ALERTS_HISTORY (
    TIMESTAMP         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EQUIPMENT_ID      VARCHAR,
    SKU_ID            VARCHAR,
    ACTION_TAKEN      VARCHAR,
    PRIORITY          VARCHAR,
    RUL_HOURS         FLOAT,
    OEM_CONSTRAINTS   VARCHAR,
    STATUS            VARCHAR
);
